project_id = "wexdqkqhslmpioyhrbvo"

[functions.broadcast-location]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.register-client]
verify_jwt = false

[functions.bootstrap-super-admin]
verify_jwt = false
